name: bia
services:
  server:
    container_name: bia
    environment:
      DB_PORT: "5432"
      DB_PWD: postgres
      DB_USER: postgres
    image: 264642482083.dkr.ecr.us-east-1.amazonaws.com/bia:666d84d
    networks:
      default: null
    ports:
    - mode: ingress
      target: 8080
      published: "80"
      protocol: tcp
networks:
  default:
    name: bia_default
